version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xline
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080