export enum WithdrawRequestStatus {
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum DepositRequestStatus {
    DEPOSIT_PENDING = "DEPOSIT_PENDING",
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum BorrowRequestStatus {
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    MONEY_SENT = "MONEY_SENT",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum RepayRequestStatus {
    REPAY_PENDING = "REPAY_PENDING",
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}
