export enum WithdrawRequestStatus {
    PENDING = "PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
    UNSUCCESSFUL_PAYMENT_PROCESSING_REQUEST = "UNSUCCESSFUL_PAYMENT_PROCESSING_REQUEST",
}

export enum DepositRequestStatus {
    PENDING = "PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum BorrowRequestStatus {
    WAITING_FOR_DEPOSIT = "WAITING_FOR_DEPOSIT",
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    MONEY_SENT = "MONEY_SENT",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum RepayRequestStatus {
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    FINISHED = "FINISHED",
    REJECTED = "REJECTED",
}

export enum ActionTypes {
    DEPOSIT,
    WITHDRAW,
    BORROW,
    REPAY,
}
